save z-max heightmapScale setting
mainsail-crew/mainsail pull request #1175
Opened 2022-11-28 13:33 UTC by vajonam

- saves the z-max heightmapScale. 
- increased the scale size to 2mm. useful for follks with not very flat beds.

2022-11-28 13:35 UTC, vajonam commented
![Peek 2022-11-28 08-32](https://user-images.githubusercontent.com/152501/204290589-6858acc5-3232-4897-863e-5f5267c5d918.gif)

2022-12-09 19:46 UTC, th33xitus requested changes
Concise spelling

2022-12-09 19:46 UTC, th33xitus commented on src/pages/Heightmap.vue
> +    get scaleGradiant(): boolean {
```suggestion
    get scaleGradient(): boolean {
```

2022-12-09 19:46 UTC, th33xitus commented on src/pages/Heightmap.vue
> +    set scaleGradiant(newVal) {
```suggestion
    set scaleGradient(newVal) {
```

2022-12-09 19:46 UTC, th33xitus commented on src/pages/Heightmap.vue
> +        if (!this.scaleGradiant) return [-0.1, 0.1]
```suggestion
        if (!this.scaleGradient) return [-0.1, 0.1]
```

2022-12-09 19:46 UTC, th33xitus commented on src/pages/Heightmap.vue
> +                                        v-model="scaleGradiant"
```suggestion
                                        v-model="scaleGradient"
```

2022-12-09 20:05 UTC, th33xitus approved these changes

2022-12-09 20:21 UTC, merged