feat: support a color or colour variable from tool change macros
mainsail-crew/mainsail pull request #1244
Opened 2023-01-21 15:40 UTC by richardjm

When set the button color will use that set from the variable.

Example macros

```
############################################################################
# Complementary functions controlling variables used by mainsail for display
############################################################################

# Requires appropriately named variables in your tool change macros (these are used my mainsail)
# [gcode_macro T0]
# variable_active: 0
# variable_color: "undefined"

[gcode_macro _SET_ACTIVE_TOOL]
description: Sets the active tool in mainsail (and all others inactive)
gcode:
  {% set TOOL = params.TOOL|default(-1)|int %}
  {% for T in range(9) %}
    {% if T == TOOL %}
      SET_GCODE_VARIABLE MACRO=T{T} VARIABLE=active VALUE=1
    {% else %}
      SET_GCODE_VARIABLE MACRO=T{T} VARIABLE=active VALUE=0
    {% endif %}
  {% endfor %}

# In SuperSlicer you can set the color variables, you also have to
# do regex post-processing to remove the # from the color for klipper
# _SET_TOOL_COLOR TOOL=0 COLOR={extruder_colour[0]}
# _SET_TOOL_COLOR TOOL=1 COLOR={extruder_colour[1]}
# ...
# _SET_TOOL_COLOR TOOL=n COLOR={extruder_colour[n]}
#
# Post processing regex
# Find: _SET_TOOL_COLOR TOOL=([0-9]+) COLOR=#([0-9A-F]+)
# Regular expression: checked
# Replace with: _SET_TOOL_COLOR TOOL=$1 COLOR=$2
[gcode_macro _SET_TOOL_COLOR]
description: Sets a color for mainsail extruder (e.g. TOOL=1 COLOR=FF00FF)
gcode:
  {% set TOOL = params.TOOL|default(-1)|int %}
  {% set COLOR = params.COLOR|default('undefined')|string %}
  SET_GCODE_VARIABLE MACRO=T{TOOL} VARIABLE=color VALUE='"{COLOR}"'

  # Requires [save_variables], for me this is provided by ercf
  SAVE_VARIABLE VARIABLE=t{TOOL}_color VALUE='"{COLOR}"'

# Reload the colors from the [save_variables] if used
[delayed_gcode _SET_TOOL_COLORS_ON_STARTUP]
initial_duration: 1
gcode:
  {% set svv = printer.save_variables.variables %}
  {% for T in range(9) %}
    _SET_TOOL_COLOR TOOL={T} COLOR={svv['t' + (T|string) + '_color']}
  {% endfor %}
```

Signed-off-by: Richard Mitchell <richardjm+mainsail@gmail.com>

2023-02-06 06:57 UTC, meteyou requested changes

2023-02-06 06:59 UTC, richardjm commented on src/store/printer/getters.ts
> +                    color: macro.variables.color ?? macro.variables.colour ?? 'null',
Yes was just trying to support both spellings of colour.

2023-02-06 11:02 UTC, zellneralex commented
```[gcode_macro _SET_TOOL_COLOR]
description: Sets a color for mainsail extruder (e.g. TOOL=1 COLOR=FF00FF)
gcode:
  {% set tool = params.TOOL|default(-1)|int %}
  # get color from rawparams and remove #
  {% set ns = namespace(color="undefined") %}
  {% for param in rawparams.split(' ') %}
    {% if 'COLOR' in param|string %}
      {% set ns.color = param[7:] %}
    {% endif %}
  {% endfor %}
  SET_GCODE_VARIABLE MACRO=T{tool} VARIABLE=color VALUE='"{ns.color}"'
  # Requires [save_variables], for me this is provided by ercf
  {% if printer.save_variables.variables is defined %}
    SAVE_VARIABLE VARIABLE=t{tool}_color VALUE='"{ns.color}"'
  {% endif %}``` avoids the need of a post processing of the gcode

2023-02-06 11:36 UTC, zellneralex commented
That version will handle both correct so you can use #12345 or 12345 as COLOR 
```
[gcode_macro _SET_TOOL_COLOR]
description: Sets a color for mainsail extruder
gcode:
  {% set tool = params.TOOL|default(-1)|int %}
  # get color from rawparams and remove #
  {% set ns = namespace(color="undefined") %}
  #{% set rawparams_list = rawparams.split(' ') %}
  {% for param in rawparams.split(' ') %}
    {% if 'COLOR' in param|string %}
      {% set rawcolor = (param.split('='))[1] %}
      {% set ns.color = rawcolor if rawcolor[0]|lower in ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f'] else rawcolor[1:] %}
    {% endif %}
  {% endfor %}
  SET_GCODE_VARIABLE MACRO=T{tool} VARIABLE=color VALUE='"{ns.color}"'
  # Requires [save_variables], for me this is provided by ercf
  {% if printer.save_variables.variables is defined %}
    SAVE_VARIABLE VARIABLE=t{tool}_color VALUE='"{ns.color}"'
  {% endif %}
```

2023-02-06 21:19 UTC, richardjm commented on src/components/panels/ExtruderControlPanel.vue
> +                            :style="'background-color: #' + tool.color + ';'"
This is what already happens as the default value for tool.color is null via
```
color: macro.variables.colour ?? null,
```

2023-02-06 21:53 UTC, meteyou commented on src/components/panels/ExtruderControlPanel.vue
> +                            :style="'background-color: #' + tool.color + ';'"
But even if the color is null, `background-color: #;` is executed

2023-02-06 23:23 UTC, richardjm commented on src/components/panels/ExtruderControlPanel.vue
> +                            :style="'background-color: #' + tool.color + ';'"
Not as far as I can see as the null coalesces into null removing the background-color. Can't find the exact documentation for it but as you can see in the screenshot style is completely removed.

2023-02-07 06:38 UTC, richardjm commented
Slight modification to the macro as it wasn't working with `_SET_TOOL_COLOR tool=1 color=FF0000` (lower case COLOR argument)

```
# _SET_TOOL_COLOR TOOL=<id> COLOR=<color>
# e.g. _SET_TOOL_COLOR TOOL=0 COLOR=#112233
[gcode_macro _SET_TOOL_COLOR]
description: Sets a color for mainsail extruder
gcode:
  {% set tool = params.TOOL|default(-1)|int %}
  # get color from rawparams and and remove the # char from the color code if present
  {% set ns = namespace(color="undefined") %}
  {% for param in rawparams.split(' ') %}
    {% if 'COLOR' in param|string|upper %}
      {% set rawcolor = (param.split('='))[1] %}
      {% set ns.color = rawcolor if rawcolor[0]|lower in ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f'] else rawcolor[1:] %}
    {% endif %}
  {% endfor %}
  SET_GCODE_VARIABLE MACRO=T{tool} VARIABLE=color VALUE='"{ns.color}"'
  # Requires [save_variables], for me this is provided by ercf
  {% if printer.save_variables is defined %}
    SAVE_VARIABLE VARIABLE=t{tool}_color VALUE='"{ns.color}"'
  {% endif %}
  ```

2023-02-07 06:46 UTC, richardjm commented on src/components/panels/ExtruderControlPanel.vue
> +                            :style="'background-color: #' + tool.color + ';'"
Modified to use object setting which I believe I have confirmed now - https://shorturl.at/rO347

2023-02-07 07:08 UTC, richardjm commented on src/store/printer/getters.ts
> +                    color: macro.variables.color ?? macro.variables.colour ?? 'null',
Changed to use `color` spelling consistently

2023-02-07 10:14 UTC, zellneralex commented
I promise that will be the last iteration. Now we also insure that only COLOR will work as parameter and not anything that includes COLOR in the parameter name
```
# _SET_TOOL_COLOR TOOL=<id> COLOR=<color>
# e.g. _SET_TOOL_COLOR TOOL=0 COLOR=#112233
[gcode_macro _SET_TOOL_COLOR]
description: Sets a color for mainsail extruder
gcode:
  {% set tool = params.TOOL|default(-1)|int %}
  # get color from rawparams and and remove the # char from the color code if present
  {% set ns = namespace(color="undefined") %}
  {% for param in rawparams.split(' ') %}
    {% if (param.split('='))[0]|lower == 'color' %}
      {% set rawcolor = (param.split('='))[1] %}
      {% set ns.color = rawcolor if rawcolor[0]|lower in ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f'] else rawcolor[1:] %}
    {% endif %}
  {% endfor %}
  {action_respond_info(ns.color)}
  SET_GCODE_VARIABLE MACRO=T{tool} VARIABLE=color VALUE='"{ns.color}"'
  # save value to file if [save_variables] is defined in printer.cfg
  {% if printer.save_variables is defined %}
    SAVE_VARIABLE VARIABLE=t{tool}_color VALUE='"{ns.color}"'
  {% endif %}
  ```

2023-02-07 12:15 UTC, zellneralex commented
Ok the reason for the change can be found at the mainsail discord. Will try to add the picture later.

```

# _SET_TOOL_COLOR TOOL=<id> COLOR=<color>
# e.g. _SET_TOOL_COLOR TOOL=0 COLOR=#112233
[gcode_macro _SET_TOOL_COLOR]
description: Sets a color for mainsail extruder
gcode:
  # get color and tool from rawparams and and remove the # char from the color code if present
  {% set ns = namespace(color="undefined", tool=-1) %}
  {% for param in rawparams.split(' ') %}
    {% if (param.split('='))[0]|lower == 'color' %}
      {% set rawcolor = (param.split('='))[1] %}
      {% set ns.color = rawcolor if rawcolor[0]|lower in ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f'] else rawcolor[1:] %}
    {% endif %}
    {% if (param.split('='))[0]|lower == 'tool' %}
      {% set ns.tool = (param.split('='))[1]|int %}
    {% endif %}
  {% endfor %}
  # set color if all is ok or error out
  {% if ns.tool == -1 %} 
    {action_raise_error("TOOL parameter missing")}
  {% elif printer['gcode_macro T' + ns.tool|string] is not defined %}
    {action_raise_error("No macro T%d defined" % (ns.tool))}
  {% elif printer['gcode_macro T' + ns.tool|string].color is not defined %}
    {action_raise_error("variable_color missing at macro T%d" % (ns.tool))}
  {% else %}
    SET_GCODE_VARIABLE MACRO=T{ns.tool} VARIABLE=color VALUE='"{ns.color}"'
    # save value to file if [save_variables] is defined in printer.cfg
    {% if printer.save_variables is defined %}
      SAVE_VARIABLE VARIABLE=t{ns.tool}_color VALUE='"{ns.color}"'
    {% endif %}
  {% endif %}
```

2023-02-08 20:46 UTC, richardjm commented on src/components/panels/ExtruderControlPanel.vue
> +                            :style="'background-color: #' + tool.color + ';'"
Wasn't to check the new code?

2023-02-10 19:31 UTC, meteyou commented on src/store/printer/getters.ts
> +                    color: macro.variables.color ?? macro.variables.colour ?? 'null',
ohhh... i overlooked the `colour` <> `color` difference

2023-02-10 22:09 UTC, meteyou approved these changes

2023-02-12 07:24 UTC, richardjm commented on src/store/printer/getters.ts
> +                    color: macro.variables.color ?? macro.variables.colour ?? 'null',
I've just re-instated that. Anything else I need to do in order to get this merged?

2023-02-18 14:03 UTC, merged