chore: add PWA caching and cache updater
mainsail-crew/mainsail pull request #1421
Opened 2023-06-18 13:12 UTC by meteyou

## Description

This PR add PWA workbox to cache all assets to run Mainsail offline and add a updater function/dialog.

## Related Tickets & Documents

no related tickes

## Mobile & Desktop Screenshots/Recordings

![image](https://github.com/mainsail-crew/mainsail/assets/8167632/02aff9ac-71dd-48a9-af57-133b38c2d84c)

## [optional] Are there any post-deployment tasks we need to perform?

2023-06-18 13:13 UTC, meteyou commented
@QuinnDamerell if you want to double-check the cache function. This is the PR for it.

2023-06-18 13:38 UTC, th33xitus requested changes

2023-06-18 13:38 UTC, th33xitus commented on src/locales/de.json
> +            "DescriptionNeedUpdate": "Der locale Cache ist veraltet und muss aktualisiert werden. Bitte klicke auf den Button unten, um den Cache zu aktualisieren."
```suggestion
            "DescriptionNeedUpdate": "Der lokale Cache ist veraltet und muss aktualisiert werden. Bitte klicke auf den Button unten, um den Cache zu aktualisieren."
```

2023-06-18 13:47 UTC, th33xitus approved these changes

2023-06-18 15:35 UTC, QuinnDamerell commented
Amazing! Nice work!

2023-06-19 08:26 UTC, pataar commented
AFAIK a PWA doesn't work on a non-https based application. Aside from that, it looks good to me!

2023-06-19 09:02 UTC, meteyou commented on src/components/TheServiceWorker.vue
> +                <v-btn text color="primary" @click="update">update</v-btn>
ohhh thank you! I have completely overlooked that.

2023-06-19 09:13 UTC, meteyou commented
> AFAIK a PWA doesn't work on a non-https based application. Aside from that, it looks good to me!

I tested it with a reverse proxy to get a valid lets encrypted certificate. I also see very little use for single setups. This feature is more useful for octoprinteverywhere integration or similar use cases.

Thx for your review!

2023-06-19 12:05 UTC, pataar commented
> > AFAIK a PWA doesn't work on a non-https based application. Aside from that, it looks good to me!
> 
> I tested it with a reverse proxy to get a valid lets encrypted certificate. I also see very little use for single setups. This feature is more useful for octoprinteverywhere integration or similar use cases.
> 
> Thx for your review!

With pleasure!

2023-06-19 12:38 UTC, pataar commented
@dependabot merge

2023-06-19 14:34 UTC, QuinnDamerell commented
I didn’t think about this only working on https sites. That’s probably why more users didn’t hit this before now. But as you pointed out, for sites that reverse proxy Mainsail like mine, (https://octoeverywhere.com) having the local cache is so nice! 

@meteyou you’re welcome to use my service for testing if it helps you at all. It’s free and provides unlimited data, so it might be helpful to you. On top of that, I’m more than happy to add any features you need that would help you to test!

It’s really a shame it’s not easier to generate per-user certs for .local domains. In modern times it would be nice to even have encryption on your LAN.

2023-06-19 14:50 UTC, meteyou commented
Thx! I will test it with octoeverywhere (i have it also installed on my small V2). I used this guide for installing it: [https://notthebe.ee/blog/easy-ssl-in-homelab-dns01/](https://notthebe.ee/blog/easy-ssl-in-homelab-dns01/)

The browser also blocked self-signed certs for PWA... So I think it's close to impossible for not linux experienced users to install a certificate for the printer him/her self...

2023-06-19 17:58 UTC, th33xitus approved these changes

2023-06-19 18:15 UTC, merged