feat: add optional background color for big gcode thumbnails
mainsail-crew/mainsail pull request #1535
Opened 2023-08-27 11:14 UTC by meteyou

## Description

This PR adds a optional background color to gcode thumbnails.

## Related Tickets & Documents

fixes: #1507 

## Mobile & Desktop Screenshots/Recordings

Start print dialog:
![image](https://github.com/mainsail-crew/mainsail/assets/8167632/deb26e79-8d3f-4d53-a3fd-b247997e27e5)

Status panel:
![image](https://github.com/mainsail-crew/mainsail/assets/8167632/93371474-06b0-4dfe-931b-8d4d3c511ede)

Gcode list:
![image](https://github.com/mainsail-crew/mainsail/assets/8167632/ff641d70-e142-4121-8286-6dda5d7f8dd0)

Settings:
![image](https://github.com/mainsail-crew/mainsail/assets/8167632/f9950c93-f2e2-4ff7-949c-9605791e501b)

## [optional] Are there any post-deployment tasks we need to perform?

none

2023-08-27 11:21 UTC, dw-0 requested changes

2023-08-27 11:21 UTC, dw-0 commented on src/locales/en.json
> +            "BigThumbnailBackground": "Large thumbnail background",
```suggestion
            "BigThumbnailBackground": "Large thumbnail background color",
```

2023-09-04 13:09 UTC, EmJay276 commented
Is it possible to add an "autodetection" of the background color based on the image color?
Dark picture => light background
Bright picture => dark background

2023-09-04 13:25 UTC, EmJay276 commented
@meteyou 
This here seems to work without a big library
https://stackoverflow.com/questions/38211798/detect-if-image-is-dark-light-and-addclass-dark-light-to-parent

2023-09-16 09:27 UTC, meteyou commented
@EmJay276 hmm... that could work, but is a a bigger rework. can you please open a new FR with this link? so i can add this for the next release. for this release, i would just merge this PR and extend it with the next one.

2023-10-07 10:40 UTC, dw-0 approved these changes

2023-10-07 10:54 UTC, merged