feat(Temperatures): add menu to open Settings & turn off heaters
mainsail-crew/mainsail pull request #2103
Opened 2024-12-29 09:41 UTC by meteyou

## Description

This PR adds a ContextMenu to each entry in the Temperature Panel to open the Settings dialog and for heaters add an option to turn of this specific heater.

## Related Tickets & Documents

none

## Mobile & Desktop Screenshots/Recordings

If heater has a target temp:
![image](https://github.com/user-attachments/assets/a3e9fcef-3b7a-4e38-a825-2abb01985bf1)

If heater has 0 as target temp:
![image](https://github.com/user-attachments/assets/b7f8a6ed-0af2-48c9-8df0-02e2b170c42c)

If the line is no heater:
![image](https://github.com/user-attachments/assets/e644a04b-afa2-4ccb-b809-6f26ffc3b95d)

## [optional] Are there any post-deployment tasks we need to perform?

none

2024-12-29 13:09 UTC, dw-0 requested changes

2024-12-29 13:09 UTC, dw-0 commented on src/components/panels/Temperature/TemperaturePanelListItem.vue
> +    openContentMenu(event: MouseEvent) {
```suggestion
    openContextMenu(event: MouseEvent) {
```

2024-12-29 13:09 UTC, dw-0 commented on src/components/panels/Temperature/TemperaturePanelListItem.vue
> +    <tr v-longpress:600="(e) => openContentMenu(e)" @contextmenu.prevent="openContentMenu($event)">
```suggestion
    <tr v-longpress:600="(e) => openContextMenu(e)" @contextmenu.prevent="openContextMenu($event)">
```

2024-12-29 16:58 UTC, meteyou commented on src/components/panels/Temperature/TemperaturePanelListItem.vue
> +    openContentMenu(event: MouseEvent) {
thx! fixed

2025-02-23 21:27 UTC, rackrick approved these changes

2025-02-24 06:44 UTC, dw-0 approved these changes

2025-02-24 06:59 UTC, merged