Update Home Page and Setup Guides
mainsail-crew/mainsail pull request #478
Opened 2021-12-19 13:51 UTC by prcutler

Hi,

These are my first commits to Mainsail's docs, so if I didn't do something right or you don't like the changes, I won't be offended! :) Just let me know what you would like changed and I'm happy to help.

I've gone through the home page and the setup guide for edits.  As I'm getting used to the tone and style of the docs, I just start by reading and updating what's there.  

Generally the way I've been taught is think about translations and accessibility when writing docs.  I try to limit contractions (don't vs do not), use simpler language to make it easier for translation, and limit parentheses (). 

I'll keep reviewing and sending some edits in and then I'll start helping write some of the newer chapters for the next release.

Thanks for reviewing and let me know the feedback for what I should change.

2021-12-19 16:31 UTC, meteyou commented on docs/configurations/necessary-cfg.md
> +These macros control the current print job.
`[pause_resume]`is only to enable the PAUSE/RESUME commands in klipper...

2021-12-26 16:57 UTC, prcutler commented
Hi,

I've reviewed and edited all of the Update guides.  Thank you to whomever wrote the documentation, it's always easier to edit than create!

I've tried to improve the spelling and grammar to improve readability.  I've also tried to remove contractions (don't vs do not), shorthand (config vs configuration), file names, etc. to make it easier for translators.

If there any mistakes or if anything doesn't make sense, please let me know and I'm happy to fix them.  I can take the feedback.  :)

2022-01-01 17:41 UTC, lixxbox commented on docs/index.md
> +- Control power devices such as relays, TPLink and Tasmota devices, and more)
remove ) at the end

2022-01-01 17:41 UTC, lixxbox commented on docs/index.md
> +- Customizable user interface includinglogos, backgrounds, and custom CSS
includinglogos -> missing whitespace

2022-01-01 17:45 UTC, lixxbox commented on docs/update-guide/klipper.md
> +Restart Klipper using the command `sudo service klipper restart` and check the `klippy.log`.  if Klipper startsed correctly without any errors you may continue.
typo: startsed

2022-01-01 17:51 UTC, prcutler commented
Thanks!  Sorry I missed some of these.  I'll get the changes in by tomorrow.

2022-01-01 17:54 UTC, lixxbox requested changes
I made two small comments. if they are fixed, i think it can be merged.
Enabling the update manager via the mainsail editor is something we can do later.

2022-01-03 08:51 UTC, lixxbox approved these changes

2022-01-03 09:10 UTC, merged